# Generated by Django 3.2.5 on 2021-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_head',
            field=models.CharField(max_length=100),
        ),
    ]
