# Generated by Django 3.2.5 on 2021-07-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210725_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='user_data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
