# Generated by Django 3.2.5 on 2021-07-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcomment_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='user_data',
        ),
    ]
