# Generated by Django 3.2.5 on 2021-07-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='blog/img'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='', upload_to='projects/img'),
        ),
    ]
