# Generated by Django 3.2.5 on 2021-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210730_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='project_views', to='blog.IpModel'),
        ),
    ]
