# Generated by Django 3.2.5 on 2021-07-31 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_projects_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='projectlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
