# Generated by Django 3.2.5 on 2021-08-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timeStamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
