# Generated by Django 3.2.3 on 2021-08-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_views', to='blog.IpModel'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='views',
            field=models.ManyToManyField(blank=True, default=None, related_name='project_views', to='blog.IpModel'),
        ),
    ]
