# Generated by Django 3.2.3 on 2021-08-03 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_auto_20210803_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(blank=True, default='', related_name='projectlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='views',
            field=models.ManyToManyField(blank=True, default='', related_name='project_views', to='blog.IpModel'),
        ),
    ]
