# Generated by Django 3.2.3 on 2021-08-03 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20210803_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='blog.IpModel'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='projectlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='project_views', to='blog.IpModel'),
        ),
    ]
